name: Test
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        id: go
        with:
          go-version: 1.12

      - name: Checkout code
        uses: actions/checkout@v1

      - name: Test
        run: go test -v .
